/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Thu Nov 23 22:10:35 2017 */

/* parameterized module instance */
main_pll __ (.CLKI( ), .CLKOP( ), .LOCK( ));
